# Mathematical operations in Python

## Basic stuff

In [1]:
a = 9; b = 4

In [2]:
a + b

13

In [3]:
a - b

5

In [4]:
a * b

36

In [5]:
a ** b #exponentiation: 9 ** 4= 9 * 9 * 9 * 9

6561

In [6]:
a / b

2.25

In [7]:
a // b #interger division

2

In [8]:
a % b #modulo

1

In [9]:
import math

In [10]:
math.pi

3.141592653589793

In [11]:
math.sqrt(9)

3.0

In [12]:
9 ** 0.5

3.0

In [13]:
math.e #Euler's number

2.718281828459045

In [14]:
math.log(125,5) #because 5 ** 3 = 125

3.0000000000000004

In [15]:
math.log(2,32)

0.19999999999999998

In [16]:
math.log(math.e) #the default base is e

1.0

In [17]:
math.log(math.e ** 5) #a little quizz

5.0

## Comparison

In [18]:
a = 9; b = 4

In [19]:
a == b

False

In [20]:
a > b

True

In [21]:
a < b

False

In [22]:
a - b == 5

True

In [23]:
a * b != 36

False

In [24]:
a + b > 100

False

In [25]:
T = True; F = False

In [26]:
T or F

True

In [27]:
T and F

False

In [28]:
T and T

True

In [29]:
T and F

False

In [30]:
not(F)

True

In [31]:
not(True)

False

In [32]:
T ^ T # the sign ^ means EITHER ..... OR 

False

In [33]:
T ^ F

True

In [34]:
F ^ F

False

In [35]:
a = 16; b = 4

In [36]:
math.log(a , b) != 2 or a**b > 60

True

In [37]:
math.log(b, a) > 0.3 and a // b != 0 

True

## Numpy and Arrays (matrices, vectors). Warning: this maybe a bit advanced at this point, so please pay a lot of attention!!!

### Numpy
Numpy is one of the core libraries for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

A numpy array is a grid of values, **all of the same type**, and is indexed by a **tuple** of nonnegative integers. The number of dimensions is the **rank** of the array; the **shape** of an array is a tuple of integers giving the size of the array along each dimension.

For simplicity we will limit our discussion to rank-1 (1D) and rank-2 (2D) numpy arrays 

I want to repeat: indexing in Python **starts from 0**

*Question 1: Do you already know the definition of a tuple?*

In [38]:
import numpy as np
a = np.array([1, 2, 3]) #Create a rank 1 array

In [39]:
print(type(a))                     

<class 'numpy.ndarray'>


In [40]:
print(a.ndim) 

1


In [41]:
print(a.shape) 

(3,)


In [42]:
print(a[0], a[1], a[2]) 

1 2 3


In [43]:
a[0] = 5                  # Change an element of the array
print(a) 

[5 2 3]


*Question 2: Do you already know the definition of a list? Why don't we just use a list [1, 2, 3] instead of np.array([1, 2, 3])*

In [44]:
b = np.array([[1,2,3],[4,5,6]]) 
print(b) #Now you can see a matrix

[[1 2 3]
 [4 5 6]]


In [45]:
print(b.ndim) 

2


In [46]:
print(b.shape)   # number of rows, number of columns

(2, 3)


In [47]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [48]:
a = np.zeros((2,3))   # Create an array of all zeros
print(a) 

[[0. 0. 0.]
 [0. 0. 0.]]


In [49]:
b = np.ones((3,3))    # Create an array of all ones
print(b) 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
c = np.full((3,2), 7)  # Create a constant array
print(c)  

[[7 7]
 [7 7]
 [7 7]]


In [51]:
d = np.random.random((3,3))  # Create an array filled with random values between 0 and 1
print(d) 

[[0.99509931 0.23648101 0.59066476]
 [0.67112235 0.26358517 0.6899431 ]
 [0.91970787 0.7205265  0.2926472 ]]


In [52]:
e = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(e)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
entry1 = e[1, 2] #second row, third column
print(entry1)

7


In [54]:
row1 = e[1, :] #second row
print(row1)

[5 6 7 8]


In [55]:
row2 = e[1:2, :] #another way to extract the second row, so what is the difference?
print(row2)

[[5 6 7 8]]


In [56]:
print('row2 has:', row2.ndim, 'dimensions')

row2 has: 2 dimensions


In [57]:
col1 = e[:, 0]
print(col1)
print('col1 has:', col1.ndim, 'dimension')

[1 5 9]
col1 has: 1 dimension


In [58]:
col2 = e[:, 0:1]
print(col2)
print('col2 has:', col2.ndim, 'dimensions')

[[1]
 [5]
 [9]]
col2 has: 2 dimensions


Question 3: *Do you know how to add two matrices?*

In [59]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
Y = np.array([[5,8,1],[6,7,3],[4,5,9]])
print(Y)

[[5 8 1]
 [6 7 3]
 [4 5 9]]


In [61]:
# Requirement for adding two matrices: they must have the same number of rows and the same number of columns
# Exceptions may occur via 'broadcasting', but it is beyond the scope of this course, so we won't discuss it
Z = X + Y
print(Z)

[[ 6 10  4]
 [10 12  9]
 [11 13 18]]


In [62]:
U = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(U)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [63]:
print(U+Y)

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

## Reading home work: matrix multiplication
https://www.mathsisfun.com/algebra/matrix-multiplying.html

Requirement for multiplying two matrices: if you want to mulitply matrix A of size (a1, a2) and matrix B of size (b1, b2). then a2 (the no. of columns in B) must be equal to b1 (the no. of rows in B)

A square matrix has the same number of rows and columns. An identity mattix is a square matrix with 1's on its diagonal and 0's elsewhere. An identity matrix (denoted by I) has the following property: A * I = A = I * A (just like number 1 when multiplying two real numbers)

In [ ]:
identiy_matrix = np.eye(3)         # Create a 3x3 identity matrix
print(identiy_matrix ) 