# Numpy 
(Numerical Python)

In [1]:
# import Library
import numpy as np
# for the sake of simplicity we can import a library and assign a nickname to it

### Numpy Array of Rank 1

In [3]:
# Create a rank 1 array
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [7]:
a[2]

3

In [8]:
a[1]=10

In [9]:
a

array([ 1, 10,  3])

### Numpy Array of Rank 2

In [11]:
# Create a rank 2 array
b=np.array([[1,2,3],[4,5,6]])

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape

(2, 3)

In [15]:
b[1,2]

6

In [16]:
b[1,1]

5

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

In [18]:
my_array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [19]:
my_array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
my_array_2d.shape

(3, 4)

### Slicing of Numpy Array

In [ ]:
#Example: Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; 
#         b is the following array of shape (2, 2):
#        [[2 3]
#        [6 7]]

In [21]:
my_array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
slice = my_array_2d[0:2,1:3]

In [24]:
slice

array([[2, 3],
       [6, 7]])

In [ ]:
# A slice of an array is a view into the same data, so modifying it will modify the original array.

In [25]:
slice[0,1]=15

In [26]:
slice

array([[ 2, 15],
       [ 6,  7]])

In [28]:
my_array_2d

array([[ 1,  2, 15,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Datatypes

In [29]:
x=np.array([1,2])

In [30]:
x.dtype

dtype('int32')

In [32]:
x=np.array([1.5,2.5,3.5])

In [33]:
x.dtype

dtype('float64')

In [ ]:
# datatype can be self defined as well

In [34]:
x=np.array([1,2], dtype=np.int64)

In [35]:
x.dtype

dtype('int64')

### Mathematical Operations on Numpy Array

In [36]:
x=np.array([[1,2],[3,4]])

In [37]:
y=np.array([[5,6],[7,8]])

In [38]:
sum_ = x+y # Normal sum operation

In [39]:
sum_

array([[ 6,  8],
       [10, 12]])

In [40]:
np.add(x,y) #alternatively we can again use Numpy to do the sum operation:

array([[ 6,  8],
       [10, 12]])

In [44]:
diff_ =y-x

In [45]:
diff_

array([[4, 4],
       [4, 4]])

In [46]:
np.subtract(y,x)

array([[4, 4],
       [4, 4]])

In [47]:
product= x*y

In [48]:
product

array([[ 5, 12],
       [21, 32]])

In [49]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [50]:
division =x/y

In [51]:
division

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [52]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [53]:
np.sqrt(y)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [ ]:
#Numpy provides many useful functions for performing computations on arrays; one of the most useful is 'sum'

### Scipy

# Pandas

#### DataFrames in Python (Explore data analysis with Python)

In [58]:
#import the library
import pandas as pd

In [59]:
# defining a Numpy array 
my_2darray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
my_2darray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
pd.DataFrame(my_2darray) #Converting it to a Data frame:

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [62]:
# Definig a dictionary
my_dict={1:['1','3'], 2:['1','2'],3:['2','4']}

In [63]:
my_dict

{1: ['1', '3'], 2: ['1', '2'], 3: ['2', '4']}

In [64]:
pd.DataFrame(my_dict) #Converting to a Data frame

1  2  3
0  1  1  2
1  3  2  4

In [ ]:
#Take a DataFrame as input to your DataFrame

In [69]:
my_df=pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['Ist col'])

In [70]:
my_df

Ist col
0        4
1        5
2        6
3        7

In [71]:
my_df.shape

(4, 1)

In [72]:
len(my_df)

4

In [73]:
my_df.index

RangeIndex(start=0, stop=4, step=1)

In [75]:
#Take a Series as input to your DataFrame
my_series=pd.Series({'United Kingdom':'London', 'Germany':'Berlin', 'Belgium':'Brussels'})

In [76]:
my_series

United Kingdom      London
Germany             Berlin
Belgium           Brussels
dtype: object

### Initializing a new Data Frame

In [78]:
new_df= pd.DataFrame(data=np.array(([1,2,3],[4,5,6],[7,8,9])), index=[2,3,4], columns=['A','B','C'])

In [79]:
new_df

A  B  C
2  1  2  3
3  4  5  6
4  7  8  9

### Accessing elements based on index

In [80]:
#Label based
new_df.loc[2]

A    1
B    2
C    3
Name: 2, dtype: int32

In [ ]:
#integer positioned

In [81]:
new_df.iloc[2]

A    7
B    8
C    9
Name: 4, dtype: int32

### Adding a Column to a DataFrame

In [82]:
new_df['D']=[10,11,12]

In [83]:
new_df

A  B  C   D
2  1  2  3  10
3  4  5  6  11
4  7  8  9  12

#### Resetting the Index of Your DataFrame

In [87]:
df_reset=new_df.reset_index()

In [85]:
df_reset

index  A  B  C   D
0      2  1  2  3  10
1      3  4  5  6  11
2      4  7  8  9  12

### Delete Indices, Rows or Columns From a Pandas Data Frame

In [88]:
# dropping the column with label index
df_reset.drop('index', axis=1)

A  B  C   D
0  1  2  3  10
1  4  5  6  11
2  7  8  9  12

In [ ]:
#dropping the column at position 1

In [89]:
df_reset.drop(df_reset.columns[[1]],axis=1)

index  B  C   D
0      2  2  3  10
1      3  5  6  11
2      4  8  9  12

In [90]:
df_reset.drop(df_reset.index[2])

index  A  B  C   D
0      2  1  2  3  10
1      3  4  5  6  11

### Rename the Index or Columns of a Pandas DataFrame

In [92]:
#Renaming 
renamed_col=df_reset.rename(columns={'A':'apple','B':'banana','C':'orange','D':'stawberry'})

In [93]:
renamed_col

index  apple  banana  orange  stawberry
0      2      1       2       3         10
1      3      4       5       6         11
2      4      7       8       9         12

In [94]:
renamed_col.rename(index={0: 'cat',1:'dog',2:'monkey'})

index  apple  banana  orange  stawberry
cat         2      1       2       3         10
dog         3      4       5       6         11
monkey      4      7       8       9         12

In [95]:
final_dataframe=renamed_col.drop('index', axis=1)

In [96]:
final_dataframe

apple  banana  orange  stawberry
0      1       2       3         10
1      4       5       6         11
2      7       8       9         12

In [97]:
final_dataframe=final_dataframe.rename(index={0: 'cat',1:'dog',2:'monkey'})

In [98]:
final_dataframe

apple  banana  orange  stawberry
cat         1       2       3         10
dog         4       5       6         11
monkey      7       8       9         12

In [99]:
final_dataframe.replace([9],[100])

apple  banana  orange  stawberry
cat         1       2       3         10
dog         4       5       6         11
monkey      7       8     100         12

In [103]:
final_dataframe.replace(final_dataframe.loc['monkey']['orange'],9)

apple  banana  orange  stawberry
cat         1       2       3         10
dog         4       5       6         11
monkey      7       8       9         12

#### Create an Empty DataFrame

In [106]:
empty_dataframe=pd.DataFrame(np.nan, index=[0,1,2,3,4,5], columns=['A','B','C'])

In [107]:
empty_dataframe

A   B   C
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
3 NaN NaN NaN
4 NaN NaN NaN
5 NaN NaN NaN